
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-03-30T08:42:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cfef1af4528cf5a50095f81ed30ba193809adc2",
 "version": "2017.01+216.g4cfef1a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
